"""empty message

Revision ID: db3b18e7a94e
Revises: 
Create Date: 2020-11-24 22:13:32.907700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3b18e7a94e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('deposito_previo',
    sa.Column('id_deposito_previo', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('nome_solicitante', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=99), nullable=True),
    sa.Column('criador', sa.String(length=45), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_deposito_previo')
    )
    op.create_table('servico_previo',
    sa.Column('id_servico_previo', sa.Integer(), nullable=False),
    sa.Column('descricao_servico', sa.String(length=99), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('user_inicio', sa.String(length=45), nullable=True),
    sa.Column('user_fim', sa.String(length=45), nullable=True),
    sa.Column('relaizado', sa.Boolean(), nullable=True),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.Column('id_deposito_previo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_deposito_previo'], ['deposito_previo.id_deposito_previo'], ),
    sa.PrimaryKeyConstraint('id_servico_previo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico_previo')
    op.drop_table('deposito_previo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
